In [1]:
import pandas as pd
%config IPCompleter.greedy=True
df = pd.read_csv(r'..\Datasets\titanic.csv')

In [3]:
df.head()

Unnamed: 0 Cabin Embarked     Fare  Pclass            Ticket   Age  \
0           0   NaN        S   7.2500       3         A/5 21171  22.0   
1           1   C85        C  71.2833       1          PC 17599  38.0   
2           2   NaN        S   7.9250       3  STON/O2. 3101282  26.0   
3           3  C123        S  53.1000       1            113803  35.0   
4           4   NaN        S   8.0500       3            373450  35.0   

                                                Name  Parch     Sex  SibSp  \
0                            Braund, Mr. Owen Harris      0    male      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...      0  female      1   
2                             Heikkinen, Miss. Laina      0  female      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)      0  female      1   
4                           Allen, Mr. William Henry      0    male      0   

   Survived  
0       0.0  
1       1.0  
2       1.0  
3       1.0  
4       0.0

In [5]:
df.describe(include='all')

Unnamed: 0        Cabin Embarked         Fare       Pclass    Ticket  \
count   1309.000000          295     1307  1308.000000  1309.000000      1309   
unique          NaN          186        3          NaN          NaN       929   
top             NaN  C23 C25 C27        S          NaN          NaN  CA. 2343   
freq            NaN            6      914          NaN          NaN        11   
mean     654.000000          NaN      NaN    33.295479     2.294882       NaN   
std      378.020061          NaN      NaN    51.758668     0.837836       NaN   
min        0.000000          NaN      NaN     0.000000     1.000000       NaN   
25%      327.000000          NaN      NaN     7.895800     2.000000       NaN   
50%      654.000000          NaN      NaN    14.454200     3.000000       NaN   
75%      981.000000          NaN      NaN    31.275000     3.000000       NaN   
max     1308.000000          NaN      NaN   512.329200     3.000000       NaN   

                Age                  Name        Parch   Sex        SibSp  \
count   1046.000000                  1309  1309.000000  1309  1309.000000   
unique          NaN                  1307          NaN     2          NaN   
top             NaN  Connolly, Miss. Kate          NaN  male          NaN   
freq            NaN                     2          NaN   843          NaN   
mean      29.881138                   NaN     0.385027   NaN     0.498854   
std       14.413493                   NaN     0.865560   NaN     1.041658   
min        0.170000                   NaN     0.000000   NaN     0.000000   
25%       21.000000                   NaN     0.000000   NaN     0.000000   
50%       28.000000                   NaN     0.000000   NaN     0.000000   
75%       39.000000                   NaN     0.000000   NaN     1.000000   
max       80.000000                   NaN     9.000000   NaN     8.000000   

          Survived  
count   891.000000  
unique         NaN  
top            NaN  
freq           NaN  
mean      0.383838  
std       0.486592  
min       0.000000  
25%       0.000000  
50%       0.000000  
75%       1.000000  
max       1.000000

In [12]:
# df_mod=df.drop('Unnamed: 0', axis=1)
df_mod=df.drop(columns=['Unnamed: 0',])
df_mod.head()

Cabin Embarked     Fare  Pclass            Ticket   Age  \
0   NaN        S   7.2500       3         A/5 21171  22.0   
1   C85        C  71.2833       1          PC 17599  38.0   
2   NaN        S   7.9250       3  STON/O2. 3101282  26.0   
3  C123        S  53.1000       1            113803  35.0   
4   NaN        S   8.0500       3            373450  35.0   

                                                Name  Parch     Sex  SibSp  \
0                            Braund, Mr. Owen Harris      0    male      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...      0  female      1   
2                             Heikkinen, Miss. Laina      0  female      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)      0  female      1   
4                           Allen, Mr. William Henry      0    male      0   

   Survived  
0       0.0  
1       1.0  
2       1.0  
3       1.0  
4       0.0

In [13]:
import numpy as np

In [18]:
df_mod.agg([np.mean, np.std, np.min, np.max])

Fare    Pclass     Ticket        Age                         Name  \
mean   33.295479  2.294882        NaN  29.881138                          NaN   
std    51.758668  0.837836        NaN  14.413493                          NaN   
amin    0.000000  1.000000     110152   0.170000          Abbing, Mr. Anthony   
amax  512.329200  3.000000  WE/P 5735  80.000000  van Melkebeke, Mr. Philemon   

         Parch     Sex     SibSp  Survived  
mean  0.385027     NaN  0.498854  0.383838  
std   0.865560     NaN  1.041658  0.486592  
amin  0.000000  female  0.000000  0.000000  
amax  9.000000    male  8.000000  1.000000

In [22]:
df_mod.agg([np.mean, np.std, lambda x: x.min(), np.max])

Fare    Pclass     Ticket        Age  \
mean       33.295479  2.294882        NaN  29.881138   
std        51.758668  0.837836        NaN  14.413493   
<lambda>    0.000000  1.000000     110152   0.170000   
amax      512.329200  3.000000  WE/P 5735  80.000000   

                                 Name     Parch     Sex     SibSp  Survived  
mean                              NaN  0.385027     NaN  0.498854  0.383838  
std                               NaN  0.865560     NaN  1.041658  0.486592  
<lambda>          Abbing, Mr. Anthony  0.000000  female  0.000000  0.000000  
amax      van Melkebeke, Mr. Philemon  9.000000    male  8.000000  1.000000

In [25]:
df.quantile(0.33)

Unnamed: 0    431.640000
Fare            8.559325
Pclass          2.000000
Age            23.000000
Parch           0.000000
SibSp           0.000000
Survived        0.000000
Name: 0.33, dtype: float64

In [26]:
df_mod.quantile(0.66)

Fare        26.0
Pclass       3.0
Age         34.0
Parch        0.0
SibSp        0.0
Survived     1.0
Name: 0.66, dtype: float64

In [27]:
df_mod.quantile(0.99)

Fare        262.375
Pclass        3.000
Age          65.000
Parch         4.000
SibSp         5.000
Survived      1.000
Name: 0.99, dtype: float64

In [30]:
class_grouped = df_mod.groupby('Pclass')

In [33]:
for Pclass, group in class_grouped:
    print(Pclass, group.Pclass.count())

1 323
2 277
3 709


In [35]:
df['Pclass'].unique()

array([3, 1, 2], dtype=int64)

In [48]:
for Pclass in df['Pclass'].unique():
    c = len(df[df['Pclass'] == Pclass])
    print('Class:{} - count:{}'.format(Pclass, c))

Class:3 - count:709
Class:1 - count:323
Class:2 - count:277


In [47]:
xs = df['Pclass'].unique()
print (xs)
xs.sort()
print (xs)

[3 1 2]
[1 2 3]


In [51]:
df[df['Pclass'] == 3]['Age'].max()

74.0

In [54]:
third = df[df['Pclass'] == 3]
third[third.Age == third.Age.max()]

Unnamed: 0 Cabin Embarked   Fare  Pclass  Ticket   Age  \
851         851   NaN        S  7.775       3  347060  74.0   

                    Name  Parch   Sex  SibSp  Survived  
851  Svensson, Mr. Johan      0  male      0       0.0

In [63]:
Fare_min = df.Fare.min()
Fare_max = df.Fare.max()
Age_min = df.Age.min()
Age_max = df.Age.max()
df.agg({
    'Fare': lambda x: (x-Fare_min)/(Fare_max-Fare_min),
    'Age':  lambda x: (x-Age_min)/(Age_max-Age_min)
})

Fare       Age
0     0.014151  0.273456
1     0.139136  0.473882
2     0.015469  0.323563
3     0.103644  0.436302
4     0.015713  0.436302
...        ...       ...
1304  0.015713       NaN
1305  0.212559  0.486409
1306  0.014151  0.480145
1307  0.015713       NaN
1308  0.043640       NaN

[1309 rows x 2 columns]

In [66]:
df_nan_fare = df.loc[(df.Fare.isna())]
df_nan_fare

Unnamed: 0 Cabin Embarked  Fare  Pclass Ticket   Age  \
1043        1043   NaN        S   NaN       3   3701  60.5   

                    Name  Parch   Sex  SibSp  Survived  
1043  Storey, Mr. Thomas      0  male      0       NaN

In [81]:
g = df.groupby(['Embarked','Pclass'])
gg = g.groups[('S',3)]
df.loc[gg].Fare.mean()

14.435422064777327

In [82]:
df_nan_fare = df.loc[(df.Fare.isna())]
df_benchmark = df.loc[df.groupby(['Embarked','Pclass']).groups[('S',3)]]
df_nan_fare.Fare = df_benchmark.Fare.mean()
df_nan_fare

C:\Users\Judit\AppData\Roaming\Python\Python37\site-packages\pandas\core\generic.py:5209: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self[name] = value


Unnamed: 0 Cabin Embarked       Fare  Pclass Ticket   Age  \
1043        1043   NaN        S  14.435422       3   3701  60.5   

                    Name  Parch   Sex  SibSp  Survived  
1043  Storey, Mr. Thomas      0  male      0       NaN